// Curated Theme Palettes for QuranKu & Keuangan

export const THEME_PRESETS = [
  {
    id: 'teal',
    name: 'Modern Teal (Default)',
    subtitle: 'Segar, Sejuk & Menenangkan',
    iconName: 'leaf',
    previewPrimary: '#0D9488',
    previewBg: '#F8FAFC',
    previewSurface: '#FFFFFF',
    isDark: false,
    colors: {
      primary: '#0D9488',
      primaryLight: '#CCFBF1',
      primaryDark: '#0F766E',
      primarySurface: '#F0FDFA',
      brandGold: '#F59E0B',
      brandGoldLight: '#FEF3C7',
      income: '#10B981',
      incomeLight: '#ECFDF5',
      incomeDark: '#047857',
      incomeBorder: '#A7F3D0',
      expense: '#F43F5E',
      expenseLight: '#FFF1F2',
      expenseDark: '#BE123C',
      expenseBorder: '#FECDD3',
      warning: '#F59E0B',
      warningLight: '#FEF3C7',
      warningDark: '#B45309',
      accent: '#2563EB',
      accentLight: '#DBEAFE',
      accentDark: '#1D4ED8',
      accentBorder: '#BFDBFE',
      background: '#F8FAFC',
      surface: '#FFFFFF',
      surfaceLight: '#F1F5F9',
      surfaceSubtle: '#F8FAFC',
      cardLight: '#FFFFFF',
      cardWhite: '#FFFFFF',
      text: '#0F172A',
      textDark: '#0F172A',
      textSecondary: '#475569',
      textMuted: '#64748B',
      textSubtle: '#94A3B8',
      textWhite: '#FFFFFF',
      border: '#E2E8F0',
      borderDark: '#CBD5E1',
      borderLight: '#F1F5F9',
      borderFocus: '#0D9488',
      shadow: '#64748B',
      shadowLight: '#94A3B8',
    },
  },
  {
    id: 'emerald',
    name: 'Emerald Oasis',
    subtitle: 'Hijau Klasik Islami yang Elegan',
    iconName: 'moon',
    previewPrimary: '#059669',
    previewBg: '#F4FAF6',
    previewSurface: '#FFFFFF',
    isDark: false,
    colors: {
      primary: '#059669',
      primaryLight: '#D1FAE5',
      primaryDark: '#047857',
      primarySurface: '#ECFDF5',
      brandGold: '#D97706',
      brandGoldLight: '#FEF3C7',
      income: '#10B981',
      incomeLight: '#ECFDF5',
      incomeDark: '#047857',
      incomeBorder: '#A7F3D0',
      expense: '#E11D48',
      expenseLight: '#FFE4E6',
      expenseDark: '#9F1239',
      expenseBorder: '#FECDD3',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      warningDark: '#B45309',
      accent: '#0284C7',
      accentLight: '#E0F2FE',
      accentDark: '#0369A1',
      accentBorder: '#BAE6FD',
      background: '#F4FAF6',
      surface: '#FFFFFF',
      surfaceLight: '#EBF5EE',
      surfaceSubtle: '#F4FAF6',
      cardLight: '#FFFFFF',
      cardWhite: '#FFFFFF',
      text: '#064E3B',
      textDark: '#064E3B',
      textSecondary: '#374151',
      textMuted: '#6B7280',
      textSubtle: '#9CA3AF',
      textWhite: '#FFFFFF',
      border: '#D1E7D6',
      borderDark: '#B2D8BB',
      borderLight: '#EBF5EE',
      borderFocus: '#059669',
      shadow: '#064E3B',
      shadowLight: '#6B7280',
    },
  },
  {
    id: 'amber',
    name: 'Sunset Gold',
    subtitle: 'Nuansa Emas Hangat & Penuh Energi',
    iconName: 'sunny',
    previewPrimary: '#D97706',
    previewBg: '#FAF9F5',
    previewSurface: '#FFFFFF',
    isDark: false,
    colors: {
      primary: '#D97706',
      primaryLight: '#FEF3C7',
      primaryDark: '#B45309',
      primarySurface: '#FFFBEB',
      brandGold: '#D97706',
      brandGoldLight: '#FEF3C7',
      income: '#10B981',
      incomeLight: '#ECFDF5',
      incomeDark: '#047857',
      incomeBorder: '#A7F3D0',
      expense: '#E11D48',
      expenseLight: '#FFE4E6',
      expenseDark: '#BE123C',
      expenseBorder: '#FECDD3',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      warningDark: '#B45309',
      accent: '#2563EB',
      accentLight: '#DBEAFE',
      accentDark: '#1D4ED8',
      accentBorder: '#BFDBFE',
      background: '#FAF9F5',
      surface: '#FFFFFF',
      surfaceLight: '#F5F2EA',
      surfaceSubtle: '#FAF9F5',
      cardLight: '#FFFFFF',
      cardWhite: '#FFFFFF',
      text: '#1C1917',
      textDark: '#1C1917',
      textSecondary: '#44403C',
      textMuted: '#78716C',
      textSubtle: '#A8A29E',
      textWhite: '#FFFFFF',
      border: '#E7E4DC',
      borderDark: '#D6D1C4',
      borderLight: '#F5F2EA',
      borderFocus: '#D97706',
      shadow: '#78716C',
      shadowLight: '#A8A29E',
    },
  },
  {
    id: 'royal_blue',
    name: 'Ocean Royal',
    subtitle: 'Biru Mewah, Fokus & Elegan',
    iconName: 'water',
    previewPrimary: '#2563EB',
    previewBg: '#F6F9FD',
    previewSurface: '#FFFFFF',
    isDark: false,
    colors: {
      primary: '#2563EB',
      primaryLight: '#DBEAFE',
      primaryDark: '#1D4ED8',
      primarySurface: '#EFF6FF',
      brandGold: '#D97706',
      brandGoldLight: '#FEF3C7',
      income: '#10B981',
      incomeLight: '#ECFDF5',
      incomeDark: '#047857',
      incomeBorder: '#A7F3D0',
      expense: '#F43F5E',
      expenseLight: '#FFF1F2',
      expenseDark: '#BE123C',
      expenseBorder: '#FECDD3',
      warning: '#F59E0B',
      warningLight: '#FEF3C7',
      warningDark: '#B45309',
      accent: '#0D9488',
      accentLight: '#CCFBF1',
      accentDark: '#0F766E',
      accentBorder: '#99F6E4',
      background: '#F6F9FD',
      surface: '#FFFFFF',
      surfaceLight: '#EEF4FB',
      surfaceSubtle: '#F6F9FD',
      cardLight: '#FFFFFF',
      cardWhite: '#FFFFFF',
      text: '#0F172A',
      textDark: '#0F172A',
      textSecondary: '#334155',
      textMuted: '#64748B',
      textSubtle: '#94A3B8',
      textWhite: '#FFFFFF',
      border: '#DEE8F4',
      borderDark: '#CBD7E6',
      borderLight: '#EEF4FB',
      borderFocus: '#2563EB',
      shadow: '#64748B',
      shadowLight: '#94A3B8',
    },
  },
  {
    id: 'rose',
    name: 'Rose Blossom',
    subtitle: 'Nuansa Merah Muda Lembut & Anggun',
    iconName: 'heart',
    previewPrimary: '#DB2777',
    previewBg: '#FCF7F8',
    previewSurface: '#FFFFFF',
    isDark: false,
    colors: {
      primary: '#DB2777',
      primaryLight: '#FCE7F3',
      primaryDark: '#9D174D',
      primarySurface: '#FDF2F8',
      brandGold: '#D97706',
      brandGoldLight: '#FEF3C7',
      income: '#10B981',
      incomeLight: '#ECFDF5',
      incomeDark: '#047857',
      incomeBorder: '#A7F3D0',
      expense: '#E11D48',
      expenseLight: '#FFE4E6',
      expenseDark: '#BE123C',
      expenseBorder: '#FECDD3',
      warning: '#D97706',
      warningLight: '#FEF3C7',
      warningDark: '#B45309',
      accent: '#7C3AED',
      accentLight: '#EDE9FE',
      accentDark: '#6D28D9',
      accentBorder: '#DDD6FE',
      background: '#FCF7F8',
      surface: '#FFFFFF',
      surfaceLight: '#F8EEF0',
      surfaceSubtle: '#FCF7F8',
      cardLight: '#FFFFFF',
      cardWhite: '#FFFFFF',
      text: '#1C1917',
      textDark: '#1C1917',
      textSecondary: '#4A4340',
      textMuted: '#7D7571',
      textSubtle: '#A8A09C',
      textWhite: '#FFFFFF',
      border: '#F0DFE2',
      borderDark: '#E2C9CD',
      borderLight: '#F8EEF0',
      borderFocus: '#DB2777',
      shadow: '#7D7571',
      shadowLight: '#A8A09C',
    },
  },
  {
    id: 'dark_luxe',
    name: 'Dark Luxe (OLED)',
    subtitle: 'Mode Gelap Nyaman di Mata',
    iconName: 'moon',
    previewPrimary: '#2DD4BF',
    previewBg: '#090D16',
    previewSurface: '#131B2E',
    isDark: true,
    colors: {
      primary: '#2DD4BF',
      primaryLight: '#134E4A',
      primaryDark: '#14B8A6',
      primarySurface: '#0F2E2B',
      brandGold: '#FBBF24',
      brandGoldLight: '#78350F',
      income: '#34D399',
      incomeLight: '#064E3B',
      incomeDark: '#6EE7B7',
      incomeBorder: '#047857',
      expense: '#FB7185',
      expenseLight: '#4C0519',
      expenseDark: '#FDA4AF',
      expenseBorder: '#9F1239',
      warning: '#FBBF24',
      warningLight: '#78350F',
      warningDark: '#FDE68A',
      accent: '#60A5FA',
      accentLight: '#1E3A8A',
      accentDark: '#93C5FD',
      accentBorder: '#1D4ED8',
      background: '#090D16',
      surface: '#131B2E',
      surfaceLight: '#1E293B',
      surfaceSubtle: '#101626',
      cardLight: '#131B2E',
      cardWhite: '#131B2E',
      text: '#F8FAFC',
      textDark: '#F8FAFC',
      textSecondary: '#CBD5E1',
      textMuted: '#94A3B8',
      textSubtle: '#64748B',
      textWhite: '#FFFFFF',
      border: '#1E293B',
      borderDark: '#334155',
      borderLight: '#162032',
      borderFocus: '#2DD4BF',
      shadow: '#000000',
      shadowLight: '#000000',
    },
  },
];

export const DEFAULT_THEME_ID = 'teal';

export const getThemeById = (id) => {
  return THEME_PRESETS.find((t) => t.id === id) || THEME_PRESETS[0];
};

export default {
  THEME_PRESETS,
  DEFAULT_THEME_ID,
  getThemeById,
};
