// 114 Surahs Metadata in Al-Quran
export const SURAH_DATA = [
  { number: 1, name: 'الفاتحة', name_latin: 'Al-Fatihah', number_of_ayahs: 7, revelation: 'Makkiyah', meaning: 'Pembukaan' },
  { number: 2, name: 'البقرة', name_latin: 'Al-Baqarah', number_of_ayahs: 286, revelation: 'Madaniyah', meaning: 'Sapi Betina' },
  { number: 3, name: 'آل عمران', name_latin: 'Ali \'Imran', number_of_ayahs: 200, revelation: 'Madaniyah', meaning: 'Keluarga Imran' },
  { number: 4, name: 'النساء', name_latin: 'An-Nisa\'', number_of_ayahs: 176, revelation: 'Madaniyah', meaning: 'Wanita' },
  { number: 5, name: 'المائدة', name_latin: 'Al-Ma\'idah', number_of_ayahs: 120, revelation: 'Madaniyah', meaning: 'Hidangan' },
  { number: 6, name: 'الأنعام', name_latin: 'Al-An\'am', number_of_ayahs: 165, revelation: 'Makkiyah', meaning: 'Binatang Ternak' },
  { number: 7, name: 'الأعراف', name_latin: 'Al-A\'raf', number_of_ayahs: 206, revelation: 'Makkiyah', meaning: 'Tempat Tertinggi' },
  { number: 8, name: 'الأنفال', name_latin: 'Al-Anfal', number_of_ayahs: 75, revelation: 'Madaniyah', meaning: 'Rampasan Perang' },
  { number: 9, name: 'التوبة', name_latin: 'At-Taubah', number_of_ayahs: 129, revelation: 'Madaniyah', meaning: 'Pengampunan' },
  { number: 10, name: 'يونس', name_latin: 'Yunus', number_of_ayahs: 109, revelation: 'Makkiyah', meaning: 'Nabi Yunus' },
  { number: 11, name: 'هود', name_latin: 'Hud', number_of_ayahs: 123, revelation: 'Makkiyah', meaning: 'Nabi Hud' },
  { number: 12, name: 'يوسف', name_latin: 'Yusuf', number_of_ayahs: 111, revelation: 'Makkiyah', meaning: 'Nabi Yusuf' },
  { number: 13, name: 'الرعد', name_latin: 'Ar-Ra\'d', number_of_ayahs: 43, revelation: 'Madaniyah', meaning: 'Guruh' },
  { number: 14, name: 'إبراهيم', name_latin: 'Ibrahim', number_of_ayahs: 52, revelation: 'Makkiyah', meaning: 'Nabi Ibrahim' },
  { number: 15, name: 'الحجر', name_latin: 'Al-Hijr', number_of_ayahs: 99, revelation: 'Makkiyah', meaning: 'Gunung Al-Hijr' },
  { number: 16, name: 'النحل', name_latin: 'An-Nahl', number_of_ayahs: 128, revelation: 'Makkiyah', meaning: 'Lebah' },
  { number: 17, name: 'الإسراء', name_latin: 'Al-Isra\'', number_of_ayahs: 111, revelation: 'Makkiyah', meaning: 'Perjalanan Malam' },
  { number: 18, name: 'الكهف', name_latin: 'Al-Kahf', number_of_ayahs: 110, revelation: 'Makkiyah', meaning: 'Penghuni Gua' },
  { number: 19, name: 'مريم', name_latin: 'Maryam', number_of_ayahs: 98, revelation: 'Makkiyah', meaning: 'Maryam' },
  { number: 20, name: 'طه', name_latin: 'Taha', number_of_ayahs: 135, revelation: 'Makkiyah', meaning: 'Taha' },
  { number: 21, name: 'الأنبياء', name_latin: 'Al-Anbiya\'', number_of_ayahs: 112, revelation: 'Makkiyah', meaning: 'Para Nabi' },
  { number: 22, name: 'الحج', name_latin: 'Al-Hajj', number_of_ayahs: 78, revelation: 'Madaniyah', meaning: 'Haji' },
  { number: 23, name: 'المؤمنون', name_latin: 'Al-Mu\'minun', number_of_ayahs: 118, revelation: 'Makkiyah', meaning: 'Orang-Orang Mukmin' },
  { number: 24, name: 'النور', name_latin: 'An-Nur', number_of_ayahs: 64, revelation: 'Madaniyah', meaning: 'Cahaya' },
  { number: 25, name: 'الفرقان', name_latin: 'Al-Furqan', number_of_ayahs: 77, revelation: 'Makkiyah', meaning: 'Pembeda' },
  { number: 26, name: 'الشعراء', name_latin: 'Asy-Syu\'ara\'', number_of_ayahs: 227, revelation: 'Makkiyah', meaning: 'Para Penyair' },
  { number: 27, name: 'النمل', name_latin: 'An-Naml', number_of_ayahs: 93, revelation: 'Makkiyah', meaning: 'Semut' },
  { number: 28, name: 'القصص', name_latin: 'Al-Qasas', number_of_ayahs: 88, revelation: 'Makkiyah', meaning: 'Kisah-Kisah' },
  { number: 29, name: 'العنكبوت', name_latin: 'Al-\'Ankabut', number_of_ayahs: 69, revelation: 'Makkiyah', meaning: 'Laba-Laba' },
  { number: 30, name: 'الروم', name_latin: 'Ar-Rum', number_of_ayahs: 60, revelation: 'Makkiyah', meaning: 'Bangsa Romawi' },
  { number: 31, name: 'لقمان', name_latin: 'Luqman', number_of_ayahs: 34, revelation: 'Makkiyah', meaning: 'Keluarga Luqman' },
  { number: 32, name: 'السجدة', name_latin: 'As-Sajdah', number_of_ayahs: 30, revelation: 'Makkiyah', meaning: 'Sujud' },
  { number: 33, name: 'الأحزاب', name_latin: 'Al-Ahzab', number_of_ayahs: 73, revelation: 'Madaniyah', meaning: 'Golongan yang Bersekutu' },
  { number: 34, name: 'سبإ', name_latin: 'Saba\'', number_of_ayahs: 54, revelation: 'Makkiyah', meaning: 'Kaum Saba\'' },
  { number: 35, name: 'فاطر', name_latin: 'Fatir', number_of_ayahs: 45, revelation: 'Makkiyah', meaning: 'Pencipta' },
  { number: 36, name: 'يس', name_latin: 'Yasin', number_of_ayahs: 83, revelation: 'Makkiyah', meaning: 'Yasin' },
  { number: 37, name: 'الصافات', name_latin: 'As-Saffat', number_of_ayahs: 182, revelation: 'Makkiyah', meaning: 'Barisan-Barisan' },
  { number: 38, name: 'ص', name_latin: 'Sad', number_of_ayahs: 88, revelation: 'Makkiyah', meaning: 'Sad' },
  { number: 39, name: 'الزمر', name_latin: 'Az-Zumar', number_of_ayahs: 75, revelation: 'Makkiyah', meaning: 'Rombongan' },
  { number: 40, name: 'غافر', name_latin: 'Ghafir', number_of_ayahs: 85, revelation: 'Makkiyah', meaning: 'Yang Mengampuni' },
  { number: 41, name: 'فصلت', name_latin: 'Fussilat', number_of_ayahs: 54, revelation: 'Makkiyah', meaning: 'Yang Dijelaskan' },
  { number: 42, name: 'الشورى', name_latin: 'Asy-Syura', number_of_ayahs: 53, revelation: 'Makkiyah', meaning: 'Musyawarah' },
  { number: 43, name: 'الزخرف', name_latin: 'Az-Zukhruf', number_of_ayahs: 89, revelation: 'Makkiyah', meaning: 'Perhiasan' },
  { number: 44, name: 'الدخان', name_latin: 'Ad-Dukhan', number_of_ayahs: 59, revelation: 'Makkiyah', meaning: 'Kabut' },
  { number: 45, name: 'الجاثية', name_latin: 'Al-Jasiyah', number_of_ayahs: 37, revelation: 'Makkiyah', meaning: 'Yang Berlutut' },
  { number: 46, name: 'الأحقاف', name_latin: 'Al-Ahqaf', number_of_ayahs: 35, revelation: 'Makkiyah', meaning: 'Bukit Pasir' },
  { number: 47, name: 'محمد', name_latin: 'Muhammad', number_of_ayahs: 38, revelation: 'Madaniyah', meaning: 'Nabi Muhammad' },
  { number: 48, name: 'الفتح', name_latin: 'Al-Fath', number_of_ayahs: 29, revelation: 'Madaniyah', meaning: 'Kemenangan' },
  { number: 49, name: 'الحجرات', name_latin: 'Al-Hujurat', number_of_ayahs: 18, revelation: 'Madaniyah', meaning: 'Kamar-Kamar' },
  { number: 50, name: 'ق', name_latin: 'Qaf', number_of_ayahs: 45, revelation: 'Makkiyah', meaning: 'Qaf' },
  { number: 51, name: 'الذاريات', name_latin: 'Az-Zariyat', number_of_ayahs: 60, revelation: 'Makkiyah', meaning: 'Angin yang Menerbangkan' },
  { number: 52, name: 'الطور', name_latin: 'At-Tur', number_of_ayahs: 49, revelation: 'Makkiyah', meaning: 'Bukit' },
  { number: 53, name: 'النجم', name_latin: 'An-Najm', number_of_ayahs: 62, revelation: 'Makkiyah', meaning: 'Bintang' },
  { number: 54, name: 'القمر', name_latin: 'Al-Qamar', number_of_ayahs: 55, revelation: 'Makkiyah', meaning: 'Bulan' },
  { number: 55, name: 'الرحمن', name_latin: 'Ar-Rahman', number_of_ayahs: 78, revelation: 'Madaniyah', meaning: 'Yang Maha Pengasih' },
  { number: 56, name: 'الواقعة', name_latin: 'Al-Waqi\'ah', number_of_ayahs: 96, revelation: 'Makkiyah', meaning: 'Hari Kiamat' },
  { number: 57, name: 'الحديد', name_latin: 'Al-Hadid', number_of_ayahs: 29, revelation: 'Madaniyah', meaning: 'Besi' },
  { number: 58, name: 'المجادلة', name_latin: 'Al-Mujadilah', number_of_ayahs: 22, revelation: 'Madaniyah', meaning: 'Wanita yang Mengajukan Gugatan' },
  { number: 59, name: 'الحشر', name_latin: 'Al-Hasyr', number_of_ayahs: 24, revelation: 'Madaniyah', meaning: 'Pengusiran' },
  { number: 60, name: 'الممتحنة', name_latin: 'Al-Mumtahanah', number_of_ayahs: 13, revelation: 'Madaniyah', meaning: 'Wanita yang Diuji' },
  { number: 61, name: 'الصف', name_latin: 'As-Saff', number_of_ayahs: 14, revelation: 'Madaniyah', meaning: 'Barisan' },
  { number: 62, name: 'الجمعة', name_latin: 'Al-Jumu\'ah', number_of_ayahs: 11, revelation: 'Madaniyah', meaning: 'Hari Jumat' },
  { number: 63, name: 'المنافقون', name_latin: 'Al-Munafiqun', number_of_ayahs: 11, revelation: 'Madaniyah', meaning: 'Orang-Orang Munafik' },
  { number: 64, name: 'التغابن', name_latin: 'At-Taghabun', number_of_ayahs: 18, revelation: 'Madaniyah', meaning: 'Hari Dinampakkan Kesalahan' },
  { number: 65, name: 'الطلاق', name_latin: 'At-Talaq', number_of_ayahs: 12, revelation: 'Madaniyah', meaning: 'Talak' },
  { number: 66, name: 'التحريم', name_latin: 'At-Tahrim', number_of_ayahs: 12, revelation: 'Madaniyah', meaning: 'Pengharaman' },
  { number: 67, name: 'الملك', name_latin: 'Al-Mulk', number_of_ayahs: 30, revelation: 'Makkiyah', meaning: 'Kerajaan' },
  { number: 68, name: 'القلم', name_latin: 'Al-Qalam', number_of_ayahs: 52, revelation: 'Makkiyah', meaning: 'Pena' },
  { number: 69, name: 'الحاقة', name_latin: 'Al-Haqqah', number_of_ayahs: 52, revelation: 'Makkiyah', meaning: 'Hari Kiamat' },
  { number: 70, name: 'المعارج', name_latin: 'Al-Ma\'arij', number_of_ayahs: 44, revelation: 'Makkiyah', meaning: 'Tempat Naik' },
  { number: 71, name: 'نوح', name_latin: 'Nuh', number_of_ayahs: 28, revelation: 'Makkiyah', meaning: 'Nabi Nuh' },
  { number: 72, name: 'الجن', name_latin: 'Al-Jinn', number_of_ayahs: 28, revelation: 'Makkiyah', meaning: 'Jin' },
  { number: 73, name: 'المزمل', name_latin: 'Al-Muzzammil', number_of_ayahs: 20, revelation: 'Makkiyah', meaning: 'Orang yang Berselimut' },
  { number: 74, name: 'المدثر', name_latin: 'Al-Muddassir', number_of_ayahs: 56, revelation: 'Makkiyah', meaning: 'Orang yang Berkemul' },
  { number: 75, name: 'القيامة', name_latin: 'Al-Qiyamah', number_of_ayahs: 40, revelation: 'Makkiyah', meaning: 'Hari Kiamat' },
  { number: 76, name: 'الإنسان', name_latin: 'Al-Insan', number_of_ayahs: 31, revelation: 'Madaniyah', meaning: 'Manusia' },
  { number: 77, name: 'المرسلات', name_latin: 'Al-Mursalat', number_of_ayahs: 50, revelation: 'Makkiyah', meaning: 'Malaikat yang Diutus' },
  { number: 78, name: 'النبإ', name_latin: 'An-Naba\'', number_of_ayahs: 40, revelation: 'Makkiyah', meaning: 'Berita Besar' },
  { number: 79, name: 'النازعات', name_latin: 'An-Nazi\'at', number_of_ayahs: 46, revelation: 'Makkiyah', meaning: 'Malaikat yang Mencabut' },
  { number: 80, name: 'عبس', name_latin: '\'Abasa', number_of_ayahs: 42, revelation: 'Makkiyah', meaning: 'Ia Bermuka Masam' },
  { number: 81, name: 'التكوير', name_latin: 'At-Takwir', number_of_ayahs: 29, revelation: 'Makkiyah', meaning: 'Menggulung' },
  { number: 82, name: 'الانفطار', name_latin: 'Al-Infitar', number_of_ayahs: 19, revelation: 'Makkiyah', meaning: 'Terbelah' },
  { number: 83, name: 'المطففين', name_latin: 'Al-Mutaffifin', number_of_ayahs: 36, revelation: 'Makkiyah', meaning: 'Orang-Orang Curang' },
  { number: 84, name: 'الانشقاق', name_latin: 'Al-Insyiqaq', number_of_ayahs: 25, revelation: 'Makkiyah', meaning: 'Terbelah' },
  { number: 85, name: 'البروج', name_latin: 'Al-Buruj', number_of_ayahs: 22, revelation: 'Makkiyah', meaning: 'Gugusan Bintang' },
  { number: 86, name: 'الطارق', name_latin: 'At-Tariq', number_of_ayahs: 17, revelation: 'Makkiyah', meaning: 'Yang Datang di Malam Hari' },
  { number: 87, name: 'الأعلى', name_latin: 'Al-A\'la', number_of_ayahs: 19, revelation: 'Makkiyah', meaning: 'Yang Paling Tinggi' },
  { number: 88, name: 'الغاشية', name_latin: 'Al-Ghasyiyah', number_of_ayahs: 26, revelation: 'Makkiyah', meaning: 'Hari Pembalasan' },
  { number: 89, name: 'الفجر', name_latin: 'Al-Fajr', number_of_ayahs: 30, revelation: 'Makkiyah', meaning: 'Fajar' },
  { number: 90, name: 'البلد', name_latin: 'Al-Balad', number_of_ayahs: 20, revelation: 'Makkiyah', meaning: 'Negeri' },
  { number: 91, name: 'الشمس', name_latin: 'Asy-Syams', number_of_ayahs: 15, revelation: 'Makkiyah', meaning: 'Matahari' },
  { number: 92, name: 'الليل', name_latin: 'Al-Lail', number_of_ayahs: 21, revelation: 'Makkiyah', meaning: 'Malam' },
  { number: 93, name: 'الضحى', name_latin: 'Ad-Duha', number_of_ayahs: 11, revelation: 'Makkiyah', meaning: 'Waktu Dhuha' },
  { number: 94, name: 'الشرح', name_latin: 'Asy-Syarh', number_of_ayahs: 8, revelation: 'Makkiyah', meaning: 'Kelapangan' },
  { number: 95, name: 'التين', name_latin: 'At-Tin', number_of_ayahs: 8, revelation: 'Makkiyah', meaning: 'Buah Tin' },
  { number: 96, name: 'العلق', name_latin: 'Al-\'Alaq', number_of_ayahs: 19, revelation: 'Makkiyah', meaning: 'Segumpal Darah' },
  { number: 97, name: 'القدر', name_latin: 'Al-Qadr', number_of_ayahs: 5, revelation: 'Makkiyah', meaning: 'Kemuliaan' },
  { number: 98, name: 'البينة', name_latin: 'Al-Bayyinah', number_of_ayahs: 8, revelation: 'Madaniyah', meaning: 'Bukti yang Nyata' },
  { number: 99, name: 'الزلزلة', name_latin: 'Az-Zalzalah', number_of_ayahs: 8, revelation: 'Madaniyah', meaning: 'Keguncangan' },
  { number: 100, name: 'العاديات', name_latin: 'Al-\'Adiyat', number_of_ayahs: 11, revelation: 'Makkiyah', meaning: 'Kuda Perang' },
  { number: 101, name: 'القارعة', name_latin: 'Al-Qari\'ah', number_of_ayahs: 11, revelation: 'Makkiyah', meaning: 'Hari Kiamat' },
  { number: 102, name: 'التكاثر', name_latin: 'At-Takasur', number_of_ayahs: 8, revelation: 'Makkiyah', meaning: 'Bermegah-Megahan' },
  { number: 103, name: 'العصر', name_latin: 'Al-\'Asr', number_of_ayahs: 3, revelation: 'Makkiyah', meaning: 'Masa' },
  { number: 104, name: 'الهمزة', name_latin: 'Al-Humazah', number_of_ayahs: 9, revelation: 'Makkiyah', meaning: 'Pengumpat' },
  { number: 105, name: 'الفيل', name_latin: 'Al-Fil', number_of_ayahs: 5, revelation: 'Makkiyah', meaning: 'Gajah' },
  { number: 106, name: 'قريش', name_latin: 'Quraisy', number_of_ayahs: 4, revelation: 'Makkiyah', meaning: 'Suku Quraisy' },
  { number: 107, name: 'الماعون', name_latin: 'Al-Ma\'un', number_of_ayahs: 7, revelation: 'Makkiyah', meaning: 'Barang yang Berguna' },
  { number: 108, name: 'الكوثر', name_latin: 'Al-Kausar', number_of_ayahs: 3, revelation: 'Makkiyah', meaning: 'Nikmat yang Berlimpah' },
  { number: 109, name: 'الكافرون', name_latin: 'Al-Kafirun', number_of_ayahs: 6, revelation: 'Makkiyah', meaning: 'Orang-Orang Kafir' },
  { number: 110, name: 'النصر', name_latin: 'An-Nasr', number_of_ayahs: 3, revelation: 'Madaniyah', meaning: 'Pertolongan' },
  { number: 111, name: 'المسد', name_latin: 'Al-Lahab', number_of_ayahs: 5, revelation: 'Makkiyah', meaning: 'Gejolak Api' },
  { number: 112, name: 'الإخلاص', name_latin: 'Al-Ikhlas', number_of_ayahs: 4, revelation: 'Makkiyah', meaning: 'Kemurnian Keesaan Allah' },
  { number: 113, name: 'الفلق', name_latin: 'Al-Falaq', number_of_ayahs: 5, revelation: 'Makkiyah', meaning: 'Waktu Subuh' },
  { number: 114, name: 'الناس', name_latin: 'An-Nas', number_of_ayahs: 6, revelation: 'Makkiyah', meaning: 'Umat Manusia' }
];

export const getRandomSurahAyah = () => {
  const randomSurah = SURAH_DATA[Math.floor(Math.random() * SURAH_DATA.length)];
  const randomAyahNum = Math.floor(Math.random() * randomSurah.number_of_ayahs) + 1;
  return {
    surah: randomSurah.number,
    surahInfo: randomSurah,
    ayah: randomAyahNum,
  };
};

export default SURAH_DATA;
